# Select what we should cache between builds
cache:
  paths:
  - vendor/

before_script:
- echo "deb http://ftp.uk.debian.org/debian jessie-backports main" >> /etc/apt/sources.list
- apt-get update -yqq
- apt-get install -yqq git libmcrypt-dev libcurl4-gnutls-dev libvpx-dev libjpeg-dev zlib1g-dev libpng-dev libgmp3-dev libldap2-dev libsqlite3-dev libpcre3-dev ffmpeg
- pecl install xdebug
# Install PHP extensions
- docker-php-ext-install mbstring mcrypt pdo_mysql pdo_sqlite curl json zip
- docker-php-ext-enable xdebug
# Install and run Composer
- curl -sS https://getcomposer.org/installer | php
- cd src
- php ../composer.phar require phpunit/phpunit
- php ../composer.phar install

# Bring in any services we need http://docs.gitlab.com/ee/ci/docker/using_docker_images.html#what-is-a-service
# See http://docs.gitlab.com/ce/ci/services/README.html for examples.
services:
  - mysql:5.7

# Set any variables we need
variables:
  # Configure mysql environment variables (https://hub.docker.com/r/_/mysql/)
  MYSQL_DATABASE: podtube
  MYSQL_ROOT_PASSWORD: root

# Run our tests
# If Xdebug was installed you can generate a coverage report and see code coverage metrics.
test:7.1.1:
  # This file is a template, and might need editing before it works on your project.
  # Select image from https://hub.docker.com/_/php/
  image: php:7.1.1
  script:
  - vendor/bin/phpunit --configuration ../phpunit.xml --coverage-text --colors=never

test:7.0:
  # This file is a template, and might need editing before it works on your project.
  # Select image from https://hub.docker.com/_/php/
  image: php:7.0
  script:
  - vendor/bin/phpunit --configuration ../phpunit.xml --coverage-text --colors=never

test:5.6:
  # This file is a template, and might need editing before it works on your project.
  # Select image from https://hub.docker.com/_/php/
  image: php:5.6
  script:
  - vendor/bin/phpunit --configuration ../phpunit.xml --coverage-text --colors=never
  
test:latest:
  # This file is a template, and might need editing before it works on your project.
  # Select image from https://hub.docker.com/_/php/
  image: php:latest
  script:
  - vendor/bin/phpunit --configuration ../phpunit.xml --coverage-text --colors=never