language: php
php:
  - '5.4'
  - '5.5'
  - '5.6'
  - '7.0'
  - '7.1'
  - nightly
services:
  - mysql
mysql:
  username: podtube
  database: podtube
  encoding: utf-8
install: 
  - cd src
  - composer install
before_script:
  - mysql -e 'CREATE DATABASE IF NOT EXISTS podtube;'
  - cd ../